### PR TITLE
Fix #1840, Add Null check for CFE_ResourceId_FindNext

### LINKED ISSUE #1840: CFE_ResourceId_FindNext can Seg Fault
**Describe the bug**
If you pass a null for the CheckFunc argument then CFE_ResourceId_FindNext will Segmentation Fault. Also the Comments in the c file mention how it is an internal function which it currently isn't.

**Expected behavior**
There should be a null check. 
A Functional Test for that null check. 
Update the header file for the new return code

**Additional context**
new functional test should plan with https://github.com/nasa/cFE/pull/1782 

**Reporter Info**
Alex Campbell GSFC

### PR DESCRIPTION
**Pull request by zanzaben**
**Describe the contribution**
Fixes #1840
Adds Null check to CFE_ResourceId_FindNext

**Testing performed**
Build and run unit test

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 20.04

**Additional context**
If this gets into master before https://github.com/nasa/cFE/pull/1782 then a Functional Test will need to be added there. Otherwise it should be added here. 

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

### CODE REVIEW

**Review by pepepr08 — APPROVED** [review]

File: modules/resourceid/fsw/src/cfe_resourceid_api.c [hunk 1]
```diff
@@ -121,6 +121,11 @@ CFE_ResourceId_t CFE_ResourceId_FindNext(CFE_ResourceId_t StartId, uint32 TableS
     CFE_ResourceId_t CheckId;
     bool             IsTaken;
 
+    if (CheckFunc == NULL)
+    {
+        return CFE_ES_BAD_ARGUMENT;
+    }
+
```
Comment (skliper) [inline modules/resourceid/fsw/src/cfe_resourceid_api.c:128]: Suggest returning CFE_RESOURCEID_UNDEFINED... otherwise this is a conversion from an error code to a resource id type.

**Comment by skliper** [comment]
@astrogeco - maybe a hot fix?  Otherwise I don't think this will work with strict resource IDs.

**Comment by zanzaben** [comment]
> @astrogeco - maybe a hot fix? Otherwise I don't think this will work with strict resource IDs.

Crud, it doesn't work with strict resource IDs. I have a fix ready. Should I push it here?

**Comment by astrogeco** [comment]
push it to IC
