### PR TITLE
Fix #687, validate table handle prior to use

### LINKED ISSUE #687: TblHandle used before validation in CFE_TBL_Load
**Describe the bug**
TblHandle used before validation

**To Reproduce**
See code snip, invalid handle could cause fault

**Expected behavior**
Validate handle before using

**Code snips**
https://github.com/nasa/cFE/blob/8365a0c69b810e313afe0fe19cdc8987374621e3/fsw/cfe-core/src/tbl/cfe_tbl_api.c#L681-L687

**System observed on:**
In code

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by CDKnightNASA**
**Describe the contribution**
fixes a bug where a table handle is used prior to validation (used in the variable initialization at the top of CFE_TBL_Load() .)

Fix #687

**Contributor Info - All information REQUIRED for consideration of pull request**
Christopher.D.Knight@nasa.gov

### CODE REVIEW

**Comment by skliper** [comment]
Squash these (just don't assign NULL):
```
[fsw/cfe-core/src/tbl/cfe_tbl_api.c:681] -> [fsw/cfe-core/src/tbl/cfe_tbl_api.c:689]: (style) Variable 'AccessDescPtr' is reassigned a value before the old one has been used.
[fsw/cfe-core/src/tbl/cfe_tbl_api.c:682] -> [fsw/cfe-core/src/tbl/cfe_tbl_api.c:690]: (style) Variable 'RegRecPtr' is reassigned a value before the old one has been used.
[fsw/cfe-core/src/tbl/cfe_tbl_api.c:680] -> [fsw/cfe-core/src/tbl/cfe_tbl_api.c:696]: (style) Variable 'WorkingBufferPtr' is reassigned a value before the old one has been used.
```

File: fsw/cfe-core/src/tbl/cfe_tbl_api.c [hunk 1]
```diff
@@ -675,17 +675,20 @@ int32 CFE_TBL_Load( CFE_TBL_Handle_t TblHandle,
...
+    int32                       Status = 0;
+    uint32                      ThisAppId = 0;
+    CFE_TBL_LoadBuff_t         *WorkingBufferPtr = NULL;
+    CFE_TBL_AccessDescriptor_t *AccessDescPtr = NULL;
+    CFE_TBL_RegistryRec_t      *RegRecPtr = NULL;
+    char                        AppName[OS_MAX_API_NAME] = {"UNKNOWN"};
     bool                        FirstTime = false;
 
     /* Verify access rights and get a valid Application ID for calling App */
     Status = CFE_TBL_ValidateAccess(TblHandle, &ThisAppId);
```
Comment (jphickey) [inline fsw/cfe-core/src/tbl/cfe_tbl_api.c:687]: Don't we need to check `Status` here?

**Comment by CDKnightNASA** [comment]
updated, squashed, pushed, better? :)

File: fsw/cfe-core/src/tbl/cfe_tbl_api.c [hunk 2]
```diff
@@ -678,21 +678,13 @@ int32 CFE_TBL_Load( CFE_TBL_Handle_t TblHandle,
...
-    Status = CFE_TBL_ValidateAccess(TblHandle, &ThisAppId);
-
-    /* Translate AppID of caller into App Name */
-    CFE_ES_GetAppName(AppName, ThisAppId, OS_MAX_API_NAME);
-
-    /* Initialize return pointer to NULL */
-    WorkingBufferPtr = NULL;
-
-    if (Status != CFE_SUCCESS)
+    if ((Status = CFE_TBL_ValidateAccess(TblHandle, &ThisAppId)) != CFE_SUCCESS)
```
Comment (jphickey) [inline fsw/cfe-core/src/tbl/cfe_tbl_api.c:687]: I know I'm a pain (and feel free to ignore this) but isn't assignments within an "if" statement also a no-no per coding standards?  I thought there was a preference to keep assignments and conditionals separated.

Comment (skliper) [reply fsw/cfe-core/src/tbl/cfe_tbl_api.c:687]: Yup, section 3.10 of the C_Coding_Standard_20051129 that we've never seemed to have shared for some reason states: "Side effects within expressions should not be used."

Comment (CDKnightNASA) [reply fsw/cfe-core/src/tbl/cfe_tbl_api.c:687]: While I agree that side effects within expressions should be excluded, I feel this form is easy to understand, is a very common pattern in our code, and it is clear there's a side effect in the expression. I'm interested in hearing what the consensus of the CCB is with regards to this.

Sorry for the multiple pushes. I'll make the change now.

**Comment by skliper** [comment]
CCB 20200513 - Approved
