### PR TITLE
Fix #1780, RTEMS CFE_FT_Global build failure

### LINKED ISSUE #1780: RTEMS CFE_FT_Global build failure
**Describe the bug**

RTEMS CI fails due to "multiple definitions" of `CFE_FT_Global` 

```
[ 96%] Linking C shared module cfe_testcase.obj
/root/rtems-5/bin/i386-rtems5-ld: CMakeFiles/cfe_testcase.dir/src/cfe_test.c.o:(.bss+0x0): multiple definition of `CFE_FT_Global'; CMakeFiles/cfe_testcase.dir/src/cfe_test_table.c.o:(.data+0x0): first defined here
/root/rtems-5/bin/i386-rtems5-ld: CMakeFiles/cfe_testcase.dir/src/tbl_content_access_test.c.o:(.bss+0x0): multiple definition of `CFE_FT_Global'; CMakeFiles/cfe_testcase.dir/src/cfe_test_table.c.o:(.data+0x0): first defined here
/root/rtems-5/bin/i386-rtems5-ld: CMakeFiles/cfe_testcase.dir/src/tbl_content_mang_test.c.o:(.bss+0x0): multiple definition of `CFE_FT_Global'; CMakeFiles/cfe_testcase.dir/src/cfe_test_table.c.o:(.data+0x0): first defined here
/root/rtems-5/bin/i386-rtems5-ld: CMakeFiles/cfe_testcase.dir/src/tbl_information_test.c.o:(.bss+0x0): multiple definition of `CFE_FT_Global'; CMakeFiles/cfe_testcase.dir/src/cfe_test_table.c.o:(.data+0x0): first defined here
/root/rtems-5/bin/i386-rtems5-ld: CMakeFiles/cfe_testcase.dir/src/tbl_registration_test.c.o:(.bss+0x0): multiple definition of `CFE_FT_Global'; CMakeFiles/cfe_testcase.dir/src/cfe_test_table.c.o:(.data+0x0): first defined here
```

**To Reproduce**

Checkout cFS bundle at `871a2d7` then point cFE to 600fd7a320e0a11cd892bf311d490735ca132f5a

**Expected behavior**
Both Linux and RTEMS build succesfully

**Code snips**
Related to setting Table releated entries in global struct in `modules/cfe_testcase/src/cfe_test_table.c`

```c
/* Constant Table information used by all table tests */
CFE_FT_Global_t CFE_FT_Global = {
    .TblName = "TestTable", .RegisteredTblName = "CFE_TEST_APP.TestTable", .TblFilename = "test_tbl.tbl"};
```

**System observed on:**
CI build of RTEMS 4.11 and 5.0

**Additional context**
Found during IC:2021-08-10 process. 

See https://github.com/nasa/cfe/issues/1772 and https://github.com/nasa/cFS/pull/333

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**
- Fix #1780 

**Testing performed**
cFE CI and bundle CI
See succesful bundle tests at https://github.com/astrogeco/cFS/runs/3284780164

**Expected behavior changes**
No behavior change, fixes build failure on RTEMS 4.11 and 5.0

**System(s) tested on**
GitHub Actions CI

**Additional context**
Fixed as part of IC:2021-08-10

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
@astrogeco 
@nmullane

### CODE REVIEW

**Comment by astrogeco** [comment]
@nmullane here's the PR for our fix

**Review by zanzaben — APPROVED** [review]

**Comment by skliper** [comment]
Minor nit - commit message looks like it's missing a verb.  Preference would be "Fix #1780, Resolve RTEMS CFE_FT_Global build failure ..."

File: modules/cfe_testcase/src/cfe_test.c [hunk 1]
```diff
@@ -41,6 +41,11 @@ CFE_FT_Global_t CFE_FT_Global;
  */
 void CFE_TestMain(void)
 {
+    /* Constant Table information used by all table tests */
+    CFE_FT_Global.TblName           = "TestTable";
+    CFE_FT_Global.RegisteredTblName = "CFE_TEST_APP.TestTable";
+    CFE_FT_Global.TblFilename       = "test_tbl.tbl";
```
Comment (skliper) [inline modules/cfe_testcase/src/cfe_test.c:47]: If this is just used by cfe_test_table.c it's probably more appropriate to initialize there.

Comment (astrogeco) [reply modules/cfe_testcase/src/cfe_test.c:47]: It's used by multiple functions across multiple source files. The alternative is to re-initialize in each one of them or initialize them in the first one but that introduces a test execution order dependency which feels too brittle.

Comment (skliper) [reply modules/cfe_testcase/src/cfe_test.c:47]: In that case I'm good as-is.

Comment (astrogeco) [reply modules/cfe_testcase/src/cfe_test.c:47]: Specifically 

```
TBLContentAccessTestSetup();
    TBLContentMangTestSetup();
    TBLInformationTestSetup();
TBLRegistrationTestSetup();
```

An alternative would be to create a new function say `TBLTests_Setup` that only contains this initialization.

**Comment by astrogeco** [comment]
> Minor nit - commit message looks like it's missing a verb. Preference would be "Fix #1780, Resolve RTEMS CFE_FT_Global build failure ..."



> Minor nit - commit message looks like it's missing a verb. Preference would be "Fix #1780, Resolve RTEMS CFE_FT_Global build failure ..."

Nit on the nit, wouldn't "Fix" be the verb in this case?

**Comment by skliper** [comment]
> > Minor nit - commit message looks like it's missing a verb. Preference would be "Fix #1780, Resolve RTEMS CFE_FT_Global build failure ..."
> 
> > Minor nit - commit message looks like it's missing a verb. Preference would be "Fix #1780, Resolve RTEMS CFE_FT_Global build failure ..."
> 
> Nit on the nit, wouldn't "Fix" be the verb in this case?

Nope.  You are "fixing" the #issue, by verbing the subject.

**Comment by jphickey** [comment]
Not intending to start any tribal wars, but I tend to side with @astrogeco on this one - The "Fix" verb should be sufficient.  That is, if you simply take out the issue number and said "Fix RTEMS CFE_FT_Global build failure" - that still makes sense.  The `#issue` is just an additional descriptor in this case, to indicate what issue was fixed (and adhere to our pattern).

As space within the first line of an commit log is precious, I don't want to expend space on two verbs that basically mean the same thing ("Fix" and "Resolve").  Keep that for the long description part.  In some ways its like saying "ATM Machine" (another pet peeve of mine).  

That's my 2c at least - I don't really care either way, aside from the general requirement to keep the first line as short as possible (under 50 chars is ideal) so it works well with various tools/displays that use the first line of a commit message.

File: modules/cfe_testcase/src/cfe_test.c (hunk 1 above)
Comment (jphickey) [reply modules/cfe_testcase/src/cfe_test.c:47]: I actually prefer the idea of making a "Setup" function here that does this init, then it can be passed as the setup function as part of the UtTest_Add for any test that uses this table struct.  That being said, its OK as is, I wouldn't hold this up.

**Review by jphickey — APPROVED** [review]

File: modules/cfe_testcase/src/cfe_test.c (hunk 1 above)
Comment (nmullane) [reply modules/cfe_testcase/src/cfe_test.c:47]: I don't think doing it as part of the setup function would work out because there is already a setup function which is used by most but not **all** of the table tests to register a table. Also since CFE_FT_Global is already instantiated in cfe_test.c I think it would make the most sense to also perform the initialization of this data just the once either there or perhaps it could be moved into cfe_test_table.c.

Comment (astrogeco) [reply modules/cfe_testcase/src/cfe_test.c:47]: Opened an issue for future work https://github.com/nasa/cFE/issues/1797

**Comment by skliper** [comment]
> Not intending to start any tribal wars, but I tend to side with @astrogeco on this one - The "Fix" verb should be sufficient. That is, if you simply take out the issue number and said "Fix RTEMS CFE_FT_Global build failure" - that still makes sense. The `#issue` is just an additional descriptor in this case, to indicate what issue was fixed (and adhere to our pattern).
> 
> As space within the first line of an commit log is precious, I don't want to expend space on two verbs that basically mean the same thing ("Fix" and "Resolve"). Keep that for the long description part. In some ways its like saying "ATM Machine" (another pet peeve of mine).
> 
> That's my 2c at least - I don't really care either way, aside from the general requirement to keep the first line as short as possible (under 50 chars is ideal) so it works well with various tools/displays that use the first line of a commit message.

What I'm really stuck on is the commit is just restating the issue... I definitely agree saying "Fix #xxx, Fixed issue blah" (or any other synonym of "fix") isn't useful.  I agree my initial suggestion doesn't solve that.  What I'd much rather see is a summary of the changes.
