### PR TITLE
Unloading module after failed app start

### LINKED ISSUE #2615: Uncleaned Resources After Failed App Start
**Describe the bug**
When an app fails to start because of bad parameters (like invalid stack size), the module stays loaded in memory and its entry in the OS_module_table is not removed. Because of this, apps with the same name can't be started. And if multiple attempts are made to start apps with bad parameters, the OS_module_table can fill up with invalid entries, blocking new apps from starting. Since the app entries in CFE_ES_Global.AppTable are deactivated, CFE_ES_STOP_APP_CC can’t clean them up.

**Expected behavior**
If an app fails to start because of bad parameters, all resources associated with the app are cleaned up

**System observed on:**
OS: RHEL 8.10

**Reporter Info**
Tvisha Andharia - GSFC 582 intern

### PR DESCRIPTION
**Pull request by tandharia**
**Checklist (Please check before submitting)**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).

**Describe the contribution**
Fixes #2615 - Unloading module from memory when an app fails to start

**Testing performed**
Built and ran all tests

**Expected behavior changes**
If an app fails to start because of bad parameters, the module is unloaded from memory and the entry in the OS_module_table removed

**System(s) tested on**
OS: RHEL 8.10

**Contributor Info - All information REQUIRED for consideration of pull request**
Tvisha Andharia - GSFC 582 intern

### CODE REVIEW

File: modules/es/fsw/src/cfe_es_apps.c [hunk 1]
```diff
@@ -799,6 +799,10 @@ int32 CFE_ES_AppCreate(CFE_ES_AppId_t *ApplicationIdPtr, const char *AppName, co
         /*
          * Set the table entry back to free
          */
+        if (OS_ObjectIdDefined(AppRecPtr->LoadStatus.ModuleId)) {
```
Comment (RichLandau) [inline modules/es/fsw/src/cfe_es_apps.c:802]: Please be sure to follow the cFS style with braces on their own line

File: modules/es/fsw/src/cfe_es_apps.c [hunk 2]
```diff
@@ -799,6 +799,10 @@ int32 CFE_ES_AppCreate(CFE_ES_AppId_t *ApplicationIdPtr, const char *AppName, co
...
+            OS_ModuleUnload(AppRecPtr->LoadStatus.ModuleId);
```
Comment (RichLandau) [inline modules/es/fsw/src/cfe_es_apps.c:803]: Please capture the return code and log on error.

**Review by RichLandau — CHANGES_REQUESTED** [review]
The pipeline for commit style is failing, could you please fix your commit message to use the standard form that links the change to the issue?

**Review by RichLandau — APPROVED** [review]

**Comment by dzbaker** [comment]
CCB 5 December 2024: Provisionally approved pending squash of commits.
