### PR TITLE
Fix #2375, Use `size_t` for variables/parameters representing size

### LINKED ISSUE #2375: Use `size_t` for variables/parameters representing size
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
Some variables/parameters in cFE representing size could be updated to the more expressive `size_t` typedef.

Most cases are already `uint32` and are assigned values from other `size_t` types or sent into functions expecting `size_t` parameters anyway.

**Expected behavior**
Update to `size_t` where appropriate.

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #2375
  - Updated size variables/parameters to `size_t` where appropriate

**Testing performed**
GitHub CI actions all passing successfully (incl. Build + Run, Unit/Functional Tests etc.).

**Expected behavior changes**
Some signed variables changed to unsigned but it would have been illogical/impossible to input negative values in those cases.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

File: modules/es/fsw/src/cfe_es_task.c [hunk 1]
```diff
@@ -1088,8 +1088,8 @@ int32 CFE_ES_QueryAllCmd(const CFE_ES_QueryAllCmd_t *data)
         OS_close(FileDescriptor);
         CFE_ES_Global.TaskData.CommandCounter++;
         CFE_EVS_SendEvent(CFE_ES_ALL_APPS_EID, CFE_EVS_EventType_DEBUG,
-                          "App Info file written to %s, Entries=%d, FileSize=%d", QueryAllFilename, (int)EntryCount,
-                          (int)FileSize);
+                          "App Info file written to %s, Entries=%d, FileSize=%lu", QueryAllFilename, (int)EntryCount,
```
Comment (zbarnett) [inline modules/es/fsw/src/cfe_es_task.c:1091]: This could be `%zu` and then you wouldn't have to cast `FileSize` at all.

Comment (jphickey) [reply modules/es/fsw/src/cfe_es_task.c:1091]: Problem is not all "c99" compilers recognize %zu yet.... Once we update to C11 then we should be able to use the z modifier.   For now I prefer to keep the cast to unsigned long.

**Review by jphickey — APPROVED** [review]
