### PR TITLE
Fix #308, Improve SB create pipe error reporting

### LINKED ISSUE #308: CFE_SB_CreatePipe: Improve message when OS_QueueCreate fails
Currently if `OS_QueueCreate` fails in `CFE_SB_CreatePipe`, the message is just `"CreatePipeErr:OS_QueueCreate returned %d,app %s"`. It would be valuable to show the name of the error rather than (or in addition to) the numeric error code. The `OS_GetErrorName` function may help here if it's available in all of the OSAL implementations.

It may be valuable to provide other details depending on the error. For example, the message in the case of `OS_ERR_NAME_TAKEN` could indicate the name of the pipe that was requested (and is already in use).

### PR DESCRIPTION
**Pull request by CDKnightNASA**
**Describe the contribution**
Improves error reporting for CFE_SB_CreatePipe()

**Testing performed**
Standard build process, ran SB unit tests.

**Expected behavior changes**
Improvement in error reporting when using a pipe name that is already in use, or when the queue limit has been reached.

**System(s) tested on:**
Debian 9

**Additional context**
Add any other context about the contribution here.

**Contributor Info**
Christopher.D.Knight@nasa.gov

**Community contributors**
N/A

### CODE REVIEW

File: fsw/cfe-core/src/sb/cfe_sb_api.c [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
-**  GSC-18128-1, "Core Flight Executive Version 6.7"
+**  GSC-18128-1, "Core Flight Executive Version 6.6"
```
Comment (skliper) [inline fsw/cfe-core/src/sb/cfe_sb_api.c]: Should be left at 6.7

Comment (CDKnightNASA) [reply fsw/cfe-core/src/sb/cfe_sb_api.c]: fixed

**Comment by skliper** [comment]
Squashed, ready for review.

File: fsw/cfe-core/src/sb/cfe_sb_api.c [hunk 2]
```diff
@@ -160,13 +160,27 @@ int32  CFE_SB_CreatePipe(CFE_SB_PipeId_t *PipeIdPtr, uint16  Depth, const char *
...
+
+                break;
+            case OS_ERR_NO_FREE_IDS:
+                CFE_EVS_SendEventWithAppID(CFE_SB_CR_PIPE_ERR_EID,CFE_EVS_EventType_ERROR,CFE_SB.AppId,
+                    "CreatePipeErr:OS_QueueCreate failed, no free id's (app=%s)",
+                    CFE_SB_GetAppTskName(TskId,FullName));
+
+                break;
+            default:
+                CFE_EVS_SendEventWithAppID(CFE_SB_CR_PIPE_ERR_EID,CFE_EVS_EventType_ERROR,CFE_SB.AppId,
```
Comment (jphickey) [inline fsw/cfe-core/src/sb/cfe_sb_api.c]: This should either both use the OSAL-defined code (OS_ERR_NAME_TAKEN, OS_ERR_NO_FREE_IDS) or the CFE-defined equivalent (CFE_OS_ERR_NAME_TAKEN, CFE_OS_ERR_NO_FREE_IDS) but not one of each.

My preference is to use the actual OSAL return codes, the CFE wrapper ones don't add much value.

**Comment by CDKnightNASA** [comment]
I’m good with this, but is this the first time cFE sends OSAL EID’s upstream? I was under the impression that cFE always remapped OSAL EIDs to cFE EIDs.

**Comment by jphickey** [comment]
This is not sending OSAL return codes in an event - it is sending the CFE-defined event based on the OSAL return code.

Because the actual call (`OS_QueueCreate()` here) is returning e.g. OS_ERR_NAME_TAKEN and the value is not "rewritten" - it is returned directly from the encapsulating function - then that is what should be checked for here, as opposed CFE_OS_ERR_NAME_TAKEN.

**Comment by CDKnightNASA** [comment]
I stand corrected, I’m good with this.

**Comment by CDKnightNASA** [comment]
> Just to translate to a request - add unique EID's for each error (per non-open-sourced coding standard).

copy will implement by next week's CCB

**Comment by CDKnightNASA** [comment]
> Just to translate to a request - add unique EID's for each error (per non-open-sourced coding standard).

resolved

**Comment by CDKnightNASA** [comment]
> Confirm current unit tests cover these new cases, needs squash

squashed

**Comment by skliper** [comment]
CCB 20200122 - Reviewed and approved for CI pending confirmation of test coverage
